# Define a method display_board that prints a 3x3 Tic Tac Toe Board
display_board = [" ", " ", " ", " ", " ", " ", " ", " ", " "]
row1[0]
row1[1]
row1[3]
row2[4]
row2[5]
row2[6]
row3[7]
row3[8]
row3[9]
